Add Prog stack
nshki/remix-directory pull request #18
Opened 2022-06-24 21:14 UTC by kory-smith

2022-06-25 05:43 UTC, nshki requested changes

2022-06-25 05:43 UTC, nshki commented on content/stacks.json
> +      "url": "https://github.com/VulcanJS/eurodance-stack"
This one is also linking to the Eurodance Stack.

2022-06-27 17:51 UTC, kory-smith commented on content/stacks.json
> +      "url": "https://github.com/VulcanJS/eurodance-stack"
Fixed in 27005eb

2022-06-28 16:42 UTC, nshki approved these changes

2022-06-28 16:42 UTC, merged